spring:
  application:
    name: timesheet
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
